import Head from "next/head";
import BalloonContainer from "@components/FloatingBalloons";

export default function Home() {
  return (
    <>
      <Head>
        <title>Balloon Popper 9000</title>
        <meta
          name="pop fucking balloons nothing else"
          content="Generated by create next app"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <BalloonContainer totalBaloon={3} />
      </main>
    </>
  );
}
